### PR TITLE
Add fade out animation for Alerts spawned with AlertController

### PR DESCRIPTION
**Pull request by wearrrrr**
Previously, Alert items would just instantly disappear when they were removed, this is seemingly because the ListView was missing a `remove` transition. This PR features a simple fade out transition, basically just copying what `displaced` does. But you can also make it slide back by changing it to this if you prefer :)

```qml
remove: Transition {
    NumberAnimation { properties: "x"; to: d.horizontalDirection == Item.Left ? -_contentRoot.width : _contentRoot.width; duration: 500; easing.type: Easing.OutBack }
}
```

### CODE REVIEW

**Review by MarkoStanojevic12 — CHANGES_REQUESTED** [review]
In theory, this should work. But it doesn't (I think it's a Qt bug). 

The elements get removed before the animation can take place. 
An alternative approach is needed here.

(Tried it on Qt 6.8.1)

**Comment by wearrrrr** [comment]
That's strange, it seems to be working perfectly fine for me. 

https://github.com/user-attachments/assets/66dc44ca-1121-40ce-8db8-caa45e4f9ba8

I am using AlertController in a very standard way, so I'm not sure what issue you could be coming across

<https://github.com/wearrrrr/9Launcher/blob/314858411450f8d32a26f8e93d24ec09d645b8f1/src/Main.qml#L75-L78>
and
<https://github.com/wearrrrr/9Launcher/blob/314858411450f8d32a26f8e93d24ec09d645b8f1/src/Footer.qml#L144-L151>

**Comment by MarkoStanojevic12** [comment]
Does it also work with multiple notifications?

**Comment by wearrrrr** [comment]
Yup! Seems to work perfectly fine with multiple, spawning a ton of notifications seems to cause lag spikes, but this is the same behavior with or without this change :) 
https://github.com/user-attachments/assets/16665ddd-44e3-4cd3-b9c3-7a3495f60f1b

**Comment by MarkoStanojevic12** [comment]
Okay, will check again. I tried slowing down the animation so I can see clearly and with that change it was not working. I guess when it's fast enough it can make it before the listview gets hidden.

Will check out also the lag spikes, I didn't encounter any yet.

**Comment by MarkoStanojevic12** [comment]
Sorry for the late response. 
Let's do your alternative approach:

`remove: Transition {
            NumberAnimation { properties: "x"; to: d.horizontalDirection == Item.Left ? -_contentRoot.width : _contentRoot.width; duration: 500; easing.type: Easing.OutBack }
        }`
        
 Please commit that change and i'll merge the PR

**Comment by wearrrrr** [comment]
No problem! Just updated it now :)

**Review by MarkoStanojevic12 — APPROVED** [review]

**Pull request merged**
